# -*- mode: ruby -*-
# vi: set ft=ruby :

$server_hostname       = "puppe"
$server_memory         = 1024

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.0.10"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = $server_memory
  end

  config.vm.provision :shell, :inline => "#sudo yum -y update"
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "./puppet/manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "./puppet/modules"
    puppet.options = "--verbose"
  end
end
