# -*- mode: ruby -*-
# vi: set ft=ruby :

$hostname       = "puppet"
$memory         = 1024

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = $memory
  end

  config.vm.provision :shell, :inline => "
	sudo yum -y update
	sudo yum -y install https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
	sudo yum -y install puppet
	"
  config.vm.provision :puppet do |puppet|
    puppet.environment_path = "environments"
    puppet.environment = "production"
  end
end
