version: '2'
services:

 influxdb:
  image: tutum/influxdb
  container_name: influxdb
  restart: always
  environment:
    - PRE_CREATE_DB=cadvisor
    - ADMIN_USER=root
    - INFLUXDB_INIT_PWD=12qw
  ports:
    - "8083:8083"
    - "8086:8086"
  volumes:
    - $PWD/influxdb/data:/var/lib/influxdb/data
    - $PWD/influxdb/log:/var/log/influxdb

 cadvisor:
  image: google/cadvisor
  container_name: cadvisor
  links:
    - influxdb:influxdb
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxdb:8086
  restart: always
  ports:
    - "8080:8080"
  volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

 grafana:
  image: grafana/grafana
  container_name: grafana
  restart: always
  links:
    - influxdb:influxdb
  ports:
    - "3000:3000"
  volumes:
    - $PWD/grafana/data:/var/lib/grafana
    - $PWD/grafana/log:/var/log/grafana
  environment:
    - HTTP_USER=admin
    - HTTP_PASS=admin
    - INFLUXDB_HOST=influxdb
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=12qw
