version: '2'

services:
   wordpress-db:
     image: mysql:5.7
     container_name: wordpress-db
     volumes:
       - "./.data/db:/var/lib/mysql"
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - wordpress-db
     image: wordpress:latest
     container_name: wordpress
     links:
       - wordpress-db
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: wordpress-db:3306
       WORDPRESS_DB_PASSWORD: wordpress
